IS424_Project/project424/urls.py
from django.contrib import admin
from django.urls import path ,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('reg/', include("reg.urls"))
]

IS424_Project/reg/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name= "reg" 



urlpatterns=[
    path('',views.index, name='index'),
    path("login",views.login_view,name="login_view"),
    path("signup",views.signup,name="signup"),
    path('<str:cid>/display',views.display , name='display'),
    path('<str:cid>/add',views.add , name='add'),
    path('update',views.update,name='update'),
    path('<str:cid>/remove',views.remove , name='remove'),
    path("logout", views.logout_view, name="logout_view")

]

urlpatterns += staticfiles_urlpatterns()


IS424_Project/reg/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class College(models.Model):
    collegeid = models.IntegerField()
    name = models.CharField(max_length=70)

    def str(self):
        return f"{self.collegeid} ({self.name})"


class Course(models.Model):
    name =  models.CharField(max_length=70)
    instructor=models.CharField(max_length=70)
    courseid = models.CharField(max_length=30)
    hours = models.IntegerField()
    hostcollege = models.ForeignKey(College, on_delete=models.CASCADE, related_name="courses")
    dicription=models.CharField(max_length=300)


    def str(self):
        return f"course info are name: {self.name} ,id: {self.courseid} , credit Hours: {self.hours} ,Host college : {self.hostcollege}"


class Student(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    # firstName = models.CharField(max_length=64)
    # lastName = models.CharField(max_length=64)
    #studentid = models.IntegerField(blank=True)
    courses = models.ManyToManyField(Course, blank=True, related_name="students")

    def str(self):
        return f"student info are name :{self.firstName} {self.lastName}"



IS424_Project/reg/views.py
from django.http import HttpResponse
from django import forms
from django.http import HttpResponseBadRequest, HttpResponseRedirect, Http404
from django.shortcuts import render
from django.urls import reverse
from .models import Course,College,Student
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.core.exceptions import ValidationError
from django.contrib import messages
import time


# Create your views here.


def login_view(request):
    if request.method == "POST":
        username = request.POST["UserName"]
        password = request.POST["passWord"]
        
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            #return HttpResponseRedirect(reverse("index"))
            return HttpResponseRedirect("/reg/")
        else:
            user = User.objects.filter(username=username).first()
            if user is not None:
                return render(request, "reg/login.html", {"message": "Incorrect password."})  
            else:
                return render(request, "reg/login.html", {"message": "Username doesn't exist."})  
    else:
        return render(request, "reg/login.html")

def index(request):
    if not request.user.is_authenticated:
        #return HttpResponseRedirect(reverse("login_view")) 
         return HttpResponseRedirect("/reg/login") 
    sid=request.user.username
    u=User.objects.get(username=sid)
    student = Student.objects.get(user=u)
    message='Here is a list of courses to Register in'
    unreg = Course.objects.exclude(students=student).all()
    return render(request,'reg/index.html',{"courses":unreg ,'message':message })#,'student':student

def display (request,cid):#sid
    if not request.user.is_authenticated:
        #return HttpResponseRedirect(reverse("login_view")) 
         return HttpResponseRedirect("/reg/login") 
    #sid=request.user.username
    course = Course.objects.get(courseid=cid)
    #u=User.objects.get(username=sid)
    #student = Student.objects.get(user=u)
    return render(request, r"reg/display.html", {"COU": course })#"STU": student

def add(request,cid):#sid
    if not request.user.is_authenticated:
        #return HttpResponseRedirect(reverse("login_view")) 
         return HttpResponseRedirect("/reg/login") 
    if request.method == "POST":
        sid=request.user.username
        course = Course.objects.get(courseid = cid)
        u=User.objects.get(username=sid)
        student = Student.objects.get(user=u)
        student.courses.add(course)
        return HttpResponseRedirect("/reg/")
        #return HttpResponseRedirect(reverse("index")) 
    return HttpResponseRedirect("/reg/")
    


def update(request):#sid
    if not request.user.is_authenticated:
        #return HttpResponseRedirect(reverse("login_view")) 
         return HttpResponseRedirect("/reg/login") 
    sid=request.user.username
    u=User.objects.get(username=sid)
    student = Student.objects.get(user=u)
    message = "Here is a list of courses you are registered in "
    regcourses = student.courses.all()
    return render(request,"reg/update.html",{"courses":regcourses ,'message':message , "student":student})

def remove(request, cid): #sid
    if not request.user.is_authenticated:
        #return HttpResponseRedirect(reverse("login_view")) 
         return HttpResponseRedirect("/reg/login") 
    sid=request.user.username
    course = Course.objects.get(courseid = cid)
    u=User.objects.get(username=sid)
    student = Student.objects.get(user=u)
    student.courses.remove(course)
    #return HttpResponseRedirect(f"/reg/")
    #return HttpResponseRedirect(reverse("index")) 
    return HttpResponseRedirect(f"/reg/update")





def signup(request):
    if request.method == "POST":
        un = request.POST["UserName"]
        pw = request.POST["passWord"]
        fname = request.POST["firstName"]
        lname = request.POST["lastName"]
        
        # Validate non-empty inputs
        if not all([un, pw, fname, lname]):
            return render(request, "reg/signup.html", {"message": "All fields are required"})  
        # Validate username
        username_validator = UnicodeUsernameValidator()
        try:
            username_validator(un)
        except ValidationError:
            return render(request, "reg/signup.html", {"message": "All fields are required"})  
        
        if User.objects.filter(username=un).exists():
                return render(request, "reg/signup.html", {"message": "Username already exists"})
       
        # Validate password
        if len(pw) < 6:
            return render(request, "reg/signup.html", {"message": "Password must be at least 6 characters long"})  

        # Validate first and last names
        if any(char.isdigit() for char in fname) or any(char.isdigit() for char in lname):
            return render(request, "reg/signup.html", {"message": "First name and last name cannot contain numbers"})  
        

        u = User.objects.create_user(username=un, password=pw, first_name=fname, last_name=lname)
        s = Student(user=u)
        s.save()
        return render(request, "reg/login.html")
    
    return render(request, "reg/signup.html")
    
   
def logout_view(request):
    logout(request)
    return render(request, "reg/login.html")




IS424_Project/reg/templates/reg/display.html
{% extends "reg/layoutnav.html" %}

{% block x %}



<h1 class="centerElement">{{COU.name}}</h1>
<table table class="table table-hover">
    <thead>
        <th scope="col">Name</th>
        <th scope="col">Course Id</th>
        <th scope="col">Hours</th>
        <th scope="col">Department</th>
        <th scope="col">Instructor</th>
    </thead>
    <tbody>
        <tr>
            <td>{{COU.name}}</td>
            <td>{{COU.courseid}}</td>
            <td>{{COU.hours}}</td>
            <td>{{COU.hostcollege.name}}</td>
            <td>{{COU.instructor}}</td>
        </tr>

    </tbody>
</table>
<h4>Discription:</h4>
<p>{{COU.dicription}}</p>

<form action="{% url 'reg:add'  COU.courseid %}" method="post">
    {% csrf_token %}
    <!-- Submit button -->
    <div class="centerElement"> 
        <button type="submit" class="btn btn-primary btn-lg mb-4" value="Add">Add</button>
    </div>
</form>



{% endblock %}

IS424_Project/reg/templates/reg/index.html
{% extends "reg/layoutnav.html" %}

{% block x %}




<h1 class="centerElement">Courses</h1>
<!--<h5 class="center">Welcome {{student.user.username}}</h5>-->
<table class="table table-hover">
    <thead>
        <th scope="col">Course Name</th>
        <th scope="col">Course Id</th>
        <th scope="col">Credit Hours</th>
        <th scope="col">Department</th>
        <th scope="col">Add</th>

    </thead>
    <tbody>
        {% for course in courses %}
        <tr>
            <td>{{course.name}}</td>
            <td>{{course.courseid}}</td>
            <td>{{course.hours}}</td>
            <td>{{course.hostcollege.name}}</td>
            <td><a href="{% url 'reg:display'  course.courseid %}">Add & Details</a></td>



        </tr>
        {% endfor %}
    </tbody>
</table>


{% endblock %}

IS424_Project/reg/templates/reg/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% load bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}

  <link rel="stylesheet" href="{% static 'reg/styles.css' %}">
  <!--<link rel="stylesheet" href="static/reg/styles.css">-->
  
  <title>CRS</title>
  
</head>
<body>
  
  <br>
  <br>
  <br>
  <div class="d-flex align-items-center justify-content-center">
    <img src="{% static 'reg/media/logo-no-background.png' %}" class="img-fluid" alt="Logo" width="400">
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>

    
  </div>
  <div class="container">
    {% block body %}
    {% endblock %} 
  </div>
   
</body>

</html>

IS424_Project/reg/templates/reg/layoutnav.html
{% extends "reg/layout.html" %}

{% block body %}



    <div class="container">


        <nav class="navv navbar navbar-expand-sm bg-light justify-content-center navbar">
    
            <ul class="navbar-nav">
    
                <li class="nav-item">
                    <a class="nav-link ml-2 btn btn-dark" href="{% url 'reg:index' %}">
                        <h6 class="text-light">Display</h6>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link ml-2 btn btn-dark" href="{% url 'reg:update' %}">
                        <h6 class="text-light">My Courses</h6>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link ml-2 btn btn-dark" href="{% url 'reg:logout_view' %}">
                        <h6 class="text-light">Logout</h6>
                    </a>
                </li>
            </ul>
    
        </nav>
    </div>
    <div class="container containerStyle">
        {% block x %}
        {% endblock %} 
    </div>
  

{% endblock %}

IS424_Project/reg/templates/reg/login.html
{% extends "reg/layout.html" %}
{% block body %}

<div class="centerstyle">

  <form action="{% url 'reg:login_view' %}" method="post">
    {% csrf_token %}
    <div class="m-4">
      <!-- Username input -->
      <div class="form-floating mb-4">
        <input type="text" id="floatingInput" class="form-control" name="UserName" placeholder="Username" required/>
        <label for="floatingInput">Username</label>
      </div>
      <!-- Password input -->
      <div class="form-floating mb-4 ">
        <input type="password" id="floatingInput" class="form-control" name="passWord" placeholder="Password" required/>
        <label for="floatingInput">Password</label>
      </div>
      <p class=" h5 centerElement " style="color: rgb(176, 0, 0);" > {{message}}</p>


      <!-- Submit button -->
      <div class="centerElement"> 
        <button type="submit" class="btn btn-primary btn-lg mb-4" value="Login">Sign In</button>
      </div>
      
      <div class="text-center">
        <p>Not a member? <a href="{% url 'reg:signup' %}">Register</a></p>

      </div>
    </div>
  </form>
</div>




{% endblock %}

IS424_Project/reg/templates/reg/signup.html
{% extends "reg/layout.html" %}

{% block body %}

<div class="centerstyle">
  

  <form method="post">
    {% csrf_token %}

    <!-- Username input -->
    <div>
      <br>
    </div>
    <div class="form-floating mb-4">
      <input type="text" id="floatingInput" class="form-control" name="UserName" placeholder="Username" required/>
      <label for="floatingInput">Username</label>
    </div>

    <!-- First input -->
    <div class="form-floating mb-4">
      <input type="text" id="floatingInput" class="form-control" name="firstName" placeholder="First Name" required/>
      <label for="floatingInput">First Name</label>
    </div>

    <!-- Last input -->
    <div class="form-floating mb-4">
      <input type="text" id="floatingInput" class="form-control" name="lastName" placeholder="Last Name" required/>
      <label for="floatingInput">Last Name</label>
    </div>

    <!-- Password input -->
    <div class="form-floating mb-4">
      <input type="password" id="floatingInput" class="form-control" name="passWord" placeholder="Password" required/>
      <label for="floatingInput">Password</label>
    </div>
    <p class=" h5 centerElement " style="color: rgb(176, 0, 0);" > {{message}}</p>

    <!-- Submit button -->
    <!--{{urls}}-->
    <div class="centerElement"> 
      <button type="submit" class="btn btn-primary btn-lg mb-4" value="Signup">Sign Up</button>
    </div>
    <!-- Register buttons -->
    <div class="text-center">
      <p>A member? <a href="{% url 'reg:login_view' %}">Login</a></p>
    </div>
    


  </form>
</div>

{% endblock %}

IS424_Project/reg/templates/reg/update.html
{% extends "reg/layoutnav.html" %}

{% block x %}





<h1 class="centerElement">My Courses</h1>

<p class="centerElement">{{message}}</p>
<table class="table table-hover">
    <thead>
        <th scope="col">Course Name</th>
        <th scope="col">Course Id</th>
        <th scope="col">Credit Hours</th>
        <th scope="col">Department</th>
        <th scope="col">Delete Course</th>

    </thead>
    <tbody>
        {% for course in courses %}
        <tr>
            <td>{{course.name}}</td>
            <td>{{course.courseid}}</td>
            <td>{{course.hours}}</td>
            <td>{{course.hostcollege.name}}</td>
            <td>
                <a href="{% url 'reg:remove'  course.courseid %}">Drop out class</a>
            </td>



        </tr>
        {% endfor %}
    </tbody>
</table>


{% endblock %}